### ISSUE TITLE
Scope to extend to markdown or other such markup.

### ISSUE THREAD

**Issue by nbCloud91** [jbyuki/ntangle.nvim#1]
I came across this plugin on your page while checking out nabla.nvim. I am looking for tools to replace a lot of the functionalities of
Emacs org-mode. (Nabla.nvim approximates one such functionality i.e. rendering LaTeX within org-mode documents.)
I was looking for ways to replicate the org-babel literate programming functionality inside nvim. I came across a plugin called vim-medieval, it evaluates fenced code blocks within Markdown documents, but it doesn't seem to have a *tangling* function(I have submitted an issue [there](https://github.com/gpanders/vim-medieval/issues/8)) which would make it super useful. Do you think your plugin could be repurposed for such a thing?

**Comment by jbyuki** [comment]
You touched my core, among all the plugins, this one is probably the one I'm the most proud of and the one I actively use the most so repurposing will not be unless there is some serious reasons.

The primary purpose of ntangle.nvim is to tangle code. The term tangle is now used ambigously and can mainly mean two things:

* Extract and concatenate code. This is to my understanding what org-mode does
* ntangle.nvim allows sections to be referenced inside others which is more general.

The purpose of ntangle.nvim is **not** to display a rich document but rather use the tangling to code differently.  So this might be slightly different to what you're looking for.

I've seen a project which tries to replicate loosely org-mode into neovim: [shoumodip/nvim-literate](https://github.com/shoumodip/nvim-literate
). This might be what you're looking for.

Sorry if I'm not able to provide you with what you want. If you ask for any plugin idea, I will gladly consider it.

**Comment by nbCloud91** [comment]
Thanks for pointing out nvim-literate, maybe that is what suits my purpose. Also, now that I look at it, ntangle.nvim is indeed for a more general purpose referencing of code.

**Comment by jbyuki** [comment]
Thank you for your interest. 

It depends on your programming skill level I think. If you're just starting, I think it might be more of a hinderance but if you already comfortable with coding, it might be interesting to you.

Personally, I've switched completely to writing programs in a literate programming style. It can be lua, C/C++ or your favorite language.

I give a brief introduction [ntangle.vim](https://github.com/jbyuki/ntangle.vim) which is also valid for ntangle.nvim. This should give you an idea of how it works. You can also look at my recent projects which are all coded in a literate programming style. The sources are usually located in src/.

The main issue with literate programming though is:
1. It's really niche, so basically no one is using it.
2. Coding in a normal style is not compatible with a literate programming style. Meaning, if you write programs in a literate style, people usually can't touch it unless they also program in a literate style. And by point 1, this is never the case.

But there are significant advantage which made me like it:
1. You can think aloud (just like org-mode), you can write some prose which describes your code. Just like comments but better.
2. You can rearrange the code however you want.

And a lot of others but the best is probably the test it.

I would be glad if someone elses adopt this style because I think there is significant potential. Of course, if you have any additionnal requests or questions for ntangle.nvim just ask. The lack of documentation is not really helping. But I wanted to write something complete sometime.

**Comment by nbCloud91** [comment]
Yes, the modularity of the code would be a huge plus. Also, I am not a *developer*, I just write code as an end user for my academic research, so I cannot say if this style of programming will pay off for me. But I do feel there are benefits of literate programming.
