### ISSUE TITLE
Support for lsp and treesitter ?

### ISSUE THREAD

**Issue by kkharji** [jbyuki/ntangle.nvim#2]
Hey @jbyuki I wonder if the plugin support lsp and treesitter? I'm sure I might be missing the point of the plugin

**Comment by jbyuki** [comment]
Hey @tami5 , the support for treesitter is one of my main goal right now. So no you are not missing the point. You can already these projects which I started:

LSP: [ntangle-lsp](https://github.com/jbyuki/ntangle-lsp.nvim) 
Tree-sitter (partially): [tree-sitter-ntangle](https://github.com/jbyuki/tree-sitter-ntangle).

Though for tree-sitter, it's just a cheat for now. Proper support is my objective. I would need incremental tangling which requires quite sophisticated algorithms. That's why I'm trying to learn new algorithms. :sweat_smile:

**Comment by kkharji** [comment]
Oh nice to hear that. I really like this development approach as I used to develop with org before. I'm going to try soon to port on my project written in two languages (rust & nix) to ntangle, any suggestions how I might organize the source code and how it the target files regenerated in write. Thanks 

edit: typo :D

**Comment by jbyuki** [comment]
The best for me would be probably to write some proper documentation instead of trying to explain every edge case of ntangle.nvim. It has become quite complicated now. I will try to upload some doc/ tomorrow hopefully.

**Comment by jbyuki** [comment]
Out of curiosity what are the teo languages? never heard of them.

**Comment by kkharji** [comment]
> Out of curiosity what are the teo languages? never heard of them.

teo languages are set of languages that ........ I'm joking 🤣.  srry I meant to type `two` instead of `teo`,

**Comment by jbyuki** [comment]
Haha, for a second I thought "teo" was the name of of the language's creator or something. Thank you for the clarification. :relaxed:

**Comment by jbyuki** [comment]
I added some rough documentation. Feel free to read it and ask me if you don't understand something.

**Comment by kkharji** [comment]
Wow I'm really impressed of how elegant, will formatted  and clear the documentation is. Thanks a lot @jbyuki
